services:

    mysql:
        image: mysql
        hostname: mysql
        volumes:
            - 'database:/var/lib/mysql/'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - websiteDatabase

    php-apache:
        hostname: php-apache
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html/'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - websiteDatabase
        depends_on:
            - mysql

    composer:
        image: composer
        volumes:
            - '.:/app/'
        command: >
            bash -c "composer install
            && composer update"

    node:
        image: node
        volumes:
            - './:/home/node/app'
        working_dir: /home/node/app
        command: >
            bash -c "npm install
            && npm update
            && npm run compile:sass"

networks:
    websiteDatabase:
        driver: bridge

volumes:
    database:
        driver: local